# Stage 1: Build the Angular application
FROM node:14 AS build
WORKDIR /app
COPY ../client/package*.json ./
RUN npm install
COPY ../client .
RUN npm run build -- --prod

# Stage 2: Serve the built application with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/codeadventures /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]